apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    name: web
  ports:
    - name: nginx-port
      port: 31344
      nodePort: 31344
      protocol: TCP
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: empty-dir
  labels:
    name: web
spec:
  containers:
    - image: busybox:latest
      imagePullPolicy: IfNotPresent
      name: html-genertor
      volumeMounts:
        - name: html
          mountPath: /var/htdocs
      command: ["/bin/sh"]
      args: ["-c", "sleep 6000"]
    - image: nginx:alpine
      name: web
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      ports:
        - containerPort: 80
          protocol: TCP
  volumes:
    - name: html
      hostPath:
        path: /opt/web/html
        # 目录不存在则创建
        # 还支持文件或者socket 类型
        type: "DirectoryOrCreate"
