apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test
  labels:
    # 让pvc 有选择
    type: ssd
spec:
  storageClassName: fake-nfs
  capacity:
    # 定义容量
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  # 回收不会清掉卷
  persistentVolumeReclaimPolicy: Retain
  # 使用hostpath 作为底层的存储
  hostPath:
    path: "/opt/volume"
    type: "DirectoryOrCreate"