apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    name: web
  ports:
    - name: nginx-port
      port: 31344
      nodePort: 31344
      protocol: TCP
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: empty-dir
  labels:
    name: web
spec:
  containers:
    - image: busybox:latest
      imagePullPolicy: IfNotPresent
      name: html-genertor
      volumeMounts:
        - name: html
          mountPath: /var/htdocs
      command: ["/bin/sh"]
      args: ["-c", "sleep 6000"]
    - image: nginx:alpine
      name: web
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      ports:
        - containerPort: 80
          protocol: TCP
  volumes:
    - name: html
      persistentVolumeClaim:
        claimName: pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  resources:
    # 申请资源
    requests:
      storage: 1Gi
  accessModes:
    # 只有一个可读写
  - ReadWriteOnce
    # 文件系统（文件和快设备）
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    # 让pvc 有选择
    type: ssd
spec:
  capacity:
    # 定义容量
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
    - ReadWriteMany
  # 回收不会清掉卷
  persistentVolumeReclaimPolicy: Retain
  # 使用hostpath 作为底层的存储
  hostPath:
    path: "/opt/volume"
    type: "DirectoryOrCreate"