apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  storageClassName: fake-nfs
  selector:
    matchLabels:
      type: "ssd"
  resources:
    # 申请资源
    requests:
      storage: 4Gi
  accessModes:
    # 只有一个可读写
    - ReadWriteOnce
    # 文件系统（文件和快设备）
  volumeMode: Filesystem