apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
  labels:
    type: ssd
spec:
  storageClassName: fake-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/opt/volume/v1"
    type: "DirectoryOrCreate"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-2
  labels:
    type: ssd
spec:
  storageClassName: fake-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/opt/volume/v2"
    type: "DirectoryOrCreate"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-3
  labels:
    type: ssd
spec:
  storageClassName: fake-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/opt/volume/v3"
    type: "DirectoryOrCreate"
