apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
  labels:
    type: ssd
spec:
  storageClassName: fake-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/opt/volume/v1"
    type: "DirectoryOrCreate"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-2
  labels:
    type: ssd
spec:
  storageClassName: fake-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/opt/volume/v2"
    type: "DirectoryOrCreate"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-3
  labels:
    type: ssd
spec:
  storageClassName: fake-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/opt/volume/v3"
    type: "DirectoryOrCreate"
---
# headless
apiVersion: v1
kind: Service
metadata:
  name: headless
spec:
  clusterIP: None
  selector:
    type: stateful
  ports:
    # headless 的作用只是用来选择那些pod
    - port: 31344
      protocol: TCP
      targetPort: 31344
  sessionAffinity: None

---
# service
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: NodePort
  selector:
    type: stateful
  ports:
    # headless 的作用只是用来选择那些pod
    - port: 31344
      protocol: TCP
      nodePort: 31344
      targetPort: 31344
  sessionAffinity: None

# stateFull
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful
spec:
  serviceName: headless
  replicas: 3
  selector:
    matchLabels:
      type: stateful
  template:
    metadata:
      name: stateful-app
      labels:
        type: stateful
    spec:
      containers:
        - name: stateful
          image: stateful:v1
          imagePullPolicy: Never
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 31344
              name: http
          volumeMounts:
          # pvc 模板的名称
            - name: data
              mountPath: /opt/database/
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        storageClassName: fake-nfs
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce