apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: default
  lables:
    app: myapp
    tier: frontend

spec:
  containers:
    - name: myapp
      image: nginx
    - name: client
      image: busybox
      commond:
        - "bin/sh"
        - "c"
        - "sleep 3000"
