apiVersion: v1
kind: Pod
metadata:
  name: proxy
spec:
  containers:
    - name: main
      image: tutum/curl:latest
      command: ["sleep","999999"]
    - name: proxy
      image: luksa/kubectl-proxy:latest
