apiVersion: v1
kind: Pod
metadata:
  name: foo
  namespace: foo
spec:
  containers:
    - name: proxy
      image: luksa/kubectl-proxy:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: bar
  namespace: bar
spec:
  containers:
    - name: proxy
      image: luksa/kubectl-proxy:lates