apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-ex
spec:
  limits:
    # 对pod的限制
    - type: Pod
      min:
        cpu: "50m"
        memory: "5Mi"
      max:
        cpu: "100m"
        memory: "300Mi"
      # 默认最高服务质量
    - type: Container
      defaultRequest:
        cpu: "100m"
        memory: "100Mi"
      default:
        cpu: "100m"
        memory: "100Mi"
    - type: PersistentVolumeClaim
      min:
        storage: "265Mi"
      max:
        storage: "265Mi"


