apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-and-mem
spec:
  hard:
    # 限制整个命名空间的资源总量
    requests.cpu: 400m
    requests.memory: 200Mi
    limits.cpu: 600m
    limits.memory: 500Mi
    # 限制存储
    requests.storage: 500Gi
    # 限制各个对象的数量
    pods: 10
    services: 10