apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
#---
#apiVersion: v1
#kind: Service
#metadata:
#    name: nginx-service-nodeport
#spec:
#  ports:
#    - port: 8000
#      targetPort: 80
#      protocol: TCP
##  type: NodePort
#  selector:
#    name: nginx