apiVersion: v1
kind: Secret
metadata:
  name: mysql

# 这里一定要使用base64处理过的字符串
data:
  password: "cm9vdDEyMzU2Nwo="
# 使用正常的字符
stringData:
  user: "root007"
---
apiVersion: v1
kind: Pod
metadata:
  name: tools
spec:
  containers:
  - image: busybox:latest
    name: tool
    command: ["/bin/sh"]
    # 可以直接将配置传入参数
    # 格式为 args: ["$(MYSQL_USER)"]
    args: ["-c", "sleep 6000"]
    volumeMounts:
    - name: mysql
      mountPath: /test/mysql/config
  volumes:
  - name: mysql
    secret:
      secretName: mysql
      items:
        - key: password
          path: password.conf
        - key: user
          path: user.conf