apiVersion: v1
kind: Pod
metadata:
  name: downward
spec:
  containers:
    - image: busybox:latest
      name: tool
      command: ["/bin/sh"]
      # 可以直接将配置传入参数
      # 格式为 args: ["$(MYSQL_USER)"]
      args: ["-c", "sleep 99999"]
      # 从downward api中获取集群中的信息
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumeMounts:
        - name: downward
          mountPath: /opt/cluster-info
  volumes:
    - name: downward
      downwardAPI:
        items:
          # 直接生成文件
          # 不支持一个大的结构体  比如 直接写metadata
          - path: "podName"
            fieldRef:
              fieldPath: metadata.name